# Generated by Django 2.1.2 on 2019-04-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasetap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
    ]
