# Generated by Django 2.1.2 on 2018-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='patron',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='good',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated',
        ),
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='SomePurchase', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
